
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { NextUIProvider } from "@nextui-org/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <div className="py-16 flex flex-col gap-4 justify-between items-center">
            {children}
            <div className="p-4 text-sm font-semibold">
              Designed and Developed with 💖 By Takam Alex C.
            </div>
          </div>
        </NextUIProvider>

      </body>
    </html>
  );
}
